CREATE TABLE IF NOT EXISTS `admin` (
    `id` INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    `username` VARCHAR(64) NOT NULL UNIQUE,
    `password` VARCHAR(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `keys` (
    `id` INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    `user_key` VARCHAR(64) NOT NULL UNIQUE,
    `game` VARCHAR(64) NOT NULL DEFAULT 'BGMI',
    `duration` INT UNSIGNED NOT NULL DEFAULT 24,
    `max_devices` INT UNSIGNED NOT NULL DEFAULT 1,
    `devices` TEXT DEFAULT NULL,
    `status` TINYINT(1) NOT NULL DEFAULT 1,
    `expired_date` DATETIME DEFAULT NULL,
    `note` VARCHAR(255) DEFAULT NULL,
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `devices` (
    `id` INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    `key_id` INT UNSIGNED NOT NULL,
    `serial` VARCHAR(128) NOT NULL,
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (`key_id`) REFERENCES `keys`(`id`) ON DELETE CASCADE,
    UNIQUE KEY `key_serial` (`key_id`, `serial`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT INTO `admin` (`username`,`password`) VALUES
('CHARANYT','$2y$10$TKh8H1.PfWx3v3llBC0vgOdqw0eBvqhKuVIKrHmikLN.DZnxZ.yLC');
